
workspace:
  base: /go
  path: src/github.com/vmware/vic-product

pipeline:
  notify-slack:
    image: plugins/slack
    secrets:
      - source: product_slack_url
        target: slack_webhook
    username: drone
    template: "Testing. Pls ignore"
 
