# Run this using following command on root repo dir. Note that this doesn't clone repo, instead mounts existing dir into drone containers.
# drone exec --timeout "1h0m0s" --timeout.inactivity "0h45m0s" --repo.trusted .drone.local.yml
---
workspace:
  base: /go
  path: src/github.com/vmware/vic-product

pipeline:
  integration-test:
    image: ${TEST_BUILD_IMAGE=gcr.io/eminent-nation-87317/vic-integration-test:1.36}
    pull: true
    environment:
      BIN: bin
      GOPATH: /go
      PUBLIC_NETWORK: ${PUBLIC_NETWORK}
      SHELL: /bin/bash
      TEST_DATASTORE: ${TEST_DATASTORE}
      TEST_PASSWORD: ${TEST_PASSWORD}
      TEST_RESOURCE: ${TEST_RESOURCE} 
      TEST_URL: ${TEST_URL}
      TEST_USERNAME: ${TEST_USERNAME}
    volumes:
      - /tmp
    commands:
      - tests/robot-run.sh "-s 2-01-Getting-Started"

services:
  selenium-grid-hub:
    image: selenium/hub:3.7.1
    ports:
      - "4444:4444"

  selenium-node-firefox:
    image: selenium/node-firefox:3.7.1
    environment:
      SE_OPTS: "-port 4445"
      HUB_PORT_4444_TCP_ADDR: 127.0.0.1
      HUB_PORT_4444_TCP_PORT: 4444
      DISPLAY: ":98.0"
