# Run this using following command on root repo dir. Note that this doesn't clone repo, instead mounts existing dir into drone containers.
# drone exec --timeout "1h0m0s" .drone.local.yml
---
workspace:
  base: /go
  path: src/github.com/vmware/vic-product

pipeline:
  integration-test:
    image: 'gcr.io/eminent-nation-87317/vic-integration-test:1.37'
    pull: true
    privileged: true
    environment:
      BIN: bin
      GOPATH: /go
      SHELL: /bin/bash
    secrets:
      - bridge_network
      - public_network
      - test_datastore
      - test_password
      - test_resource
      - test_url
      - test_username
      - vch_timeout
    volumes:
      - /tmp
    commands:
      - tests/robot-run.sh "-s 4-01-Harbor"

services:
  selenium-grid-hub:
    image: 'selenium/hub:3.7.1'
    ports:
      - '4444:4444'
    environment:
      - GRID_TIMEOUT=180000
      - GRID_BROWSER_TIMEOUT=180000

  selenium-node-firefox-1:
    image: 'selenium/node-firefox:3.7.1'
    environment:
      SE_OPTS: '-port 4445'
      HUB_PORT_4444_TCP_ADDR: selenium-grid-hub
      HUB_PORT_4444_TCP_PORT: '4444'
      DISPLAY: ':97.0'