
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["github.com/golang/dep", "github.com/GoASTScanner/gas", "github.com/go-yaml/yaml", "github.com/golang/lint/golint"]

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "0.11.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"

[[constraint]]
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/gizak/termui"

[[constraint]]
  name = "github.com/gorilla/websocket"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/vmware/govmomi"

[[constraint]]
  name = "github.com/vmware/vic"
  branch = "master"  

[[constraint]]
  name = "github.com/vmware/vmw-guestinfo"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.19.1"

[[constraint]]
  name = "github.com/golang/dep"
  version = "0.3.2"

